require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DsController do

  # This should return the minimal set of attributes required to create a valid
  # D. As you add validations to D, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "measurement" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ds as @ds" do
      d = D.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ds).should eq([d])
    end
  end

  describe "GET show" do
    it "assigns the requested d as @d" do
      d = D.create! valid_attributes
      get :show, {:id => d.to_param}, valid_session
      assigns(:d).should eq(d)
    end
  end

  describe "GET new" do
    it "assigns a new d as @d" do
      get :new, {}, valid_session
      assigns(:d).should be_a_new(D)
    end
  end

  describe "GET edit" do
    it "assigns the requested d as @d" do
      d = D.create! valid_attributes
      get :edit, {:id => d.to_param}, valid_session
      assigns(:d).should eq(d)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new D" do
        expect {
          post :create, {:d => valid_attributes}, valid_session
        }.to change(D, :count).by(1)
      end

      it "assigns a newly created d as @d" do
        post :create, {:d => valid_attributes}, valid_session
        assigns(:d).should be_a(D)
        assigns(:d).should be_persisted
      end

      it "redirects to the created d" do
        post :create, {:d => valid_attributes}, valid_session
        response.should redirect_to(D.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved d as @d" do
        # Trigger the behavior that occurs when invalid params are submitted
        D.any_instance.stub(:save).and_return(false)
        post :create, {:d => { "measurement" => "invalid value" }}, valid_session
        assigns(:d).should be_a_new(D)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        D.any_instance.stub(:save).and_return(false)
        post :create, {:d => { "measurement" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested d" do
        d = D.create! valid_attributes
        # Assuming there are no other ds in the database, this
        # specifies that the D created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        D.any_instance.should_receive(:update).with({ "measurement" => "" })
        put :update, {:id => d.to_param, :d => { "measurement" => "" }}, valid_session
      end

      it "assigns the requested d as @d" do
        d = D.create! valid_attributes
        put :update, {:id => d.to_param, :d => valid_attributes}, valid_session
        assigns(:d).should eq(d)
      end

      it "redirects to the d" do
        d = D.create! valid_attributes
        put :update, {:id => d.to_param, :d => valid_attributes}, valid_session
        response.should redirect_to(d)
      end
    end

    describe "with invalid params" do
      it "assigns the d as @d" do
        d = D.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        D.any_instance.stub(:save).and_return(false)
        put :update, {:id => d.to_param, :d => { "measurement" => "invalid value" }}, valid_session
        assigns(:d).should eq(d)
      end

      it "re-renders the 'edit' template" do
        d = D.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        D.any_instance.stub(:save).and_return(false)
        put :update, {:id => d.to_param, :d => { "measurement" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested d" do
      d = D.create! valid_attributes
      expect {
        delete :destroy, {:id => d.to_param}, valid_session
      }.to change(D, :count).by(-1)
    end

    it "redirects to the ds list" do
      d = D.create! valid_attributes
      delete :destroy, {:id => d.to_param}, valid_session
      response.should redirect_to(ds_url)
    end
  end

end
