require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TraitsController do

  # This should return the minimal set of attributes required to create a valid
  # Trait. As you add validations to Trait, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "trait_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TraitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all traits as @traits" do
      trait = Trait.create! valid_attributes
      get :index, {}, valid_session
      assigns(:traits).should eq([trait])
    end
  end

  describe "GET show" do
    it "assigns the requested trait as @trait" do
      trait = Trait.create! valid_attributes
      get :show, {:id => trait.to_param}, valid_session
      assigns(:trait).should eq(trait)
    end
  end

  describe "GET new" do
    it "assigns a new trait as @trait" do
      get :new, {}, valid_session
      assigns(:trait).should be_a_new(Trait)
    end
  end

  describe "GET edit" do
    it "assigns the requested trait as @trait" do
      trait = Trait.create! valid_attributes
      get :edit, {:id => trait.to_param}, valid_session
      assigns(:trait).should eq(trait)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Trait" do
        expect {
          post :create, {:trait => valid_attributes}, valid_session
        }.to change(Trait, :count).by(1)
      end

      it "assigns a newly created trait as @trait" do
        post :create, {:trait => valid_attributes}, valid_session
        assigns(:trait).should be_a(Trait)
        assigns(:trait).should be_persisted
      end

      it "redirects to the created trait" do
        post :create, {:trait => valid_attributes}, valid_session
        response.should redirect_to(Trait.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trait as @trait" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trait.any_instance.stub(:save).and_return(false)
        post :create, {:trait => { "trait_name" => "invalid value" }}, valid_session
        assigns(:trait).should be_a_new(Trait)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Trait.any_instance.stub(:save).and_return(false)
        post :create, {:trait => { "trait_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trait" do
        trait = Trait.create! valid_attributes
        # Assuming there are no other traits in the database, this
        # specifies that the Trait created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Trait.any_instance.should_receive(:update).with({ "trait_name" => "MyString" })
        put :update, {:id => trait.to_param, :trait => { "trait_name" => "MyString" }}, valid_session
      end

      it "assigns the requested trait as @trait" do
        trait = Trait.create! valid_attributes
        put :update, {:id => trait.to_param, :trait => valid_attributes}, valid_session
        assigns(:trait).should eq(trait)
      end

      it "redirects to the trait" do
        trait = Trait.create! valid_attributes
        put :update, {:id => trait.to_param, :trait => valid_attributes}, valid_session
        response.should redirect_to(trait)
      end
    end

    describe "with invalid params" do
      it "assigns the trait as @trait" do
        trait = Trait.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trait.any_instance.stub(:save).and_return(false)
        put :update, {:id => trait.to_param, :trait => { "trait_name" => "invalid value" }}, valid_session
        assigns(:trait).should eq(trait)
      end

      it "re-renders the 'edit' template" do
        trait = Trait.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Trait.any_instance.stub(:save).and_return(false)
        put :update, {:id => trait.to_param, :trait => { "trait_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trait" do
      trait = Trait.create! valid_attributes
      expect {
        delete :destroy, {:id => trait.to_param}, valid_session
      }.to change(Trait, :count).by(-1)
    end

    it "redirects to the traits list" do
      trait = Trait.create! valid_attributes
      delete :destroy, {:id => trait.to_param}, valid_session
      response.should redirect_to(traits_url)
    end
  end

end
